In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('f1_strategy_dataset_v4.csv')

In [5]:
df.isnull().sum()

Driver                     0
LapNumber                  0
Compound                  66
Stint                      0
TyreLife                   0
Position                   0
LapTime (s)                0
Race                       0
Year                       0
LapTime_Delta              0
Cumulative_Degradation     0
PitStop                    0
PitNextLap                 0
RaceProgress               0
Normalized_TyreLife        0
Position_Change            0
dtype: int64

In [6]:
df.shape

(101371, 16)

In [7]:
df=df.fillna(0)

In [8]:
df.isnull().sum()

Driver                    0
LapNumber                 0
Compound                  0
Stint                     0
TyreLife                  0
Position                  0
LapTime (s)               0
Race                      0
Year                      0
LapTime_Delta             0
Cumulative_Degradation    0
PitStop                   0
PitNextLap                0
RaceProgress              0
Normalized_TyreLife       0
Position_Change           0
dtype: int64

In [9]:
df

,Driver,LapNumber,Compound,Stint,TyreLife,Position,LapTime (s),Race,Year,LapTime_Delta,Cumulative_Degradation,PitStop,PitNextLap,RaceProgress,Normalized_TyreLife,Position_Change
0,ALB,1,MEDIUM,1,2.0,17,100.625,Abu Dhabi Grand Prix,2023,0.000,0.000,0,0,0.017241,0.117647,0.0
1,ALB,2,MEDIUM,1,3.0,18,93.560,Abu Dhabi Grand Prix,2023,-7.065,-7.065,0,0,0.034483,0.176471,-1.0
2,ALB,3,MEDIUM,1,4.0,18,91.768,Abu Dhabi Grand Prix,2023,-1.792,-8.857,0,0,0.051724,0.235294,0.0
3,ALB,4,MEDIUM,1,5.0,18,91.591,Abu Dhabi Grand Prix,2023,-0.177,-9.034,0,0,0.068966,0.294118,0.0
4,ALB,5,MEDIUM,1,6.0,18,91.422,Abu Dhabi Grand Prix,2023,-0.169,-9.203,0,0,0.086207,0.352941,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101366,ZHO,52,HARD,3,29.0,12,103.373,United States Grand Prix,2022,26.850,-90.264,0,0,0.722222,0.852941,2.0
101367,ZHO,53,HARD,3,30.0,13,105.200,United States Grand Prix,2022,27.061,-88.437,0,0,0.736111,0.882353,1.0
101368,ZHO,54,HARD,3,31.0,13,104.102,United States Grand Prix,2022,27.149,-89.535,0,0,0.750000,0.911765,0.0
101369,ZHO,55,HARD,3,32.0,14,103.812,United States Grand Prix,2022,4.428,-89.825,0,0,0.763889,0.941176,-1.0
101370,ZHO,56,HARD,3,33.0,14,103.881,United States Grand Prix,2022,21.390,-89.756,0,1,0.777778,0.970588,4.0

In [10]:
df=df.drop(columns=['Driver','Race','Year'])

In [11]:
df['Compound'].unique()

array(['MEDIUM', 'HARD', 'SOFT', 'INTERMEDIATE', 'WET', 0], dtype=object)

In [12]:
df = pd.get_dummies(df, columns=['Compound'], dtype=int)

In [13]:
df

,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,PitStop,PitNextLap,RaceProgress,Normalized_TyreLife,Position_Change,Compound_0,Compound_HARD,Compound_INTERMEDIATE,Compound_MEDIUM,Compound_SOFT,Compound_WET
0,1,1,2.0,17,100.625,0.000,0.000,0,0,0.017241,0.117647,0.0,0,0,0,1,0,0
1,2,1,3.0,18,93.560,-7.065,-7.065,0,0,0.034483,0.176471,-1.0,0,0,0,1,0,0
2,3,1,4.0,18,91.768,-1.792,-8.857,0,0,0.051724,0.235294,0.0,0,0,0,1,0,0
3,4,1,5.0,18,91.591,-0.177,-9.034,0,0,0.068966,0.294118,0.0,0,0,0,1,0,0
4,5,1,6.0,18,91.422,-0.169,-9.203,0,0,0.086207,0.352941,0.0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101366,52,3,29.0,12,103.373,26.850,-90.264,0,0,0.722222,0.852941,2.0,0,1,0,0,0,0
101367,53,3,30.0,13,105.200,27.061,-88.437,0,0,0.736111,0.882353,1.0,0,1,0,0,0,0
101368,54,3,31.0,13,104.102,27.149,-89.535,0,0,0.750000,0.911765,0.0,0,1,0,0,0,0
101369,55,3,32.0,14,103.812,4.428,-89.825,0,0,0.763889,0.941176,-1.0,0,1,0,0,0,0
101370,56,3,33.0,14,103.881,21.390,-89.756,0,1,0.777778,0.970588,4.0,0,1,0,0,0,0

In [14]:
X=df.drop(columns=['PitNextLap'])
y=df['PitNextLap']

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [16]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [17]:
y_pred=model.predict(X_test)

In [18]:
accuracy=accuracy_score(y_test,y_pred)

In [19]:
accuracy

0.7515166461159063